ALTER TABLE Book ADD PRIMARY KEY (ID);
ALTER TABLE Person ADD PRIMARY KEY (ID);
ALTER TABLE Employee ADD PRIMARY KEY (ID);
ALTER TABLE Bill ADD PRIMARY KEY (ID);
ALTER TABLE BookState ADD PRIMARY KEY (ID);
ALTER TABLE Borrowing ADD PRIMARY KEY (ID);
ALTER TABLE Document ADD PRIMARY KEY (ID);
ALTER TABLE Reader ADD PRIMARY KEY (ID);
