ALTER TABLE BookState ADD CONSTRAINT FKBookState96069 FOREIGN KEY (BorrowingID) REFERENCES Borrowing (ID);
ALTER TABLE BookState ADD CONSTRAINT FKBookState253384 FOREIGN KEY (BookID) REFERENCES Book (ID);
ALTER TABLE Book ADD CONSTRAINT FKBook970415 FOREIGN KEY (DocumentID) REFERENCES Document (ID);
ALTER TABLE Reader ADD CONSTRAINT FKReader816662 FOREIGN KEY (PersonID) REFERENCES Person (ID);
ALTER TABLE Borrowing ADD CONSTRAINT FKBorrowing894720 FOREIGN KEY (ReaderID) REFERENCES Reader (ID);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee925855 FOREIGN KEY (PersonID) REFERENCES Person (ID);
ALTER TABLE Borrowing ADD CONSTRAINT FKBorrowing245447 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID);
ALTER TABLE Bill ADD CONSTRAINT FKBill751374 FOREIGN KEY (BorrowingID) REFERENCES Borrowing (ID);
